name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
      - name: User introduction
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.introduction.repository.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: phillipchaffee
          repositories_affiliations: owner, collaborator, organization_member
          base: header
          plugin_introduction: yes
          
      - name: Lines of code changed
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.lines.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: repositories
          user: phillipchaffee
          repositories_affiliations: owner, collaborator, organization_member
          plugin_lines: yes
          
      - name: Recent activity charts
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.charts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: phillipchaffee
          repositories_affiliations: owner, collaborator, organization_member
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes
          config_timezone: America/Los_Angeles
          
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: phillipchaffee
          repositories_affiliations: owner, collaborator, organization_member
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
      - name: Languages Indepth analysis
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: phillipchaffee
          repositories_affiliations: owner, collaborator, organization_member
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_sections: recently-used, most-used
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_limit: 10
          plugin_languages_recent_load: 1000
          plugin_languages_recent_days: 30
          plugin_languages_analysis_timeout: 30
          commits_authoring: Phillip Chaffee, phillipchaffee, phillipdensmorechaffee@gmail.com, phillip@voiceops.com
